name: useful_extensions
description: Package of useful extensions.
version: 0.0.1
homepage: https://github.com/vovaklh/useful_extensions

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
